name: calculadora_imc
description: "Calculadora de IMC - Console Application"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.0.0
dependencies:
  flutter:
    sdk: flutter
